import React from "react";
import ReactDOM from "react-dom";
// import App from "./Demo1/App";
// import { Todos } from "./Demo2/App";
import App from "./Demo3/App";
import "todomvc-app-css/index.css";
// import { inspect } from "@xstate/inspect";
// inspect({iframe: false});
const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
